# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Publish to NPM registry

on:
  workflow_dispatch:
    inputs:
      npm_registry:
        description: 'Custom NPM_REGISTRY'
        required: false

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      NPM_REGISTRY: ${{ github.event.inputs.npm_registry || 'https://registry.npmjs.org' }}

    strategy:
      matrix:
        node-version: [18.16.1]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        registry-url: '$NPM_REGISTRY'
    - name: Use NPM Token
      # You may pin to the exact commit or the version.
      # uses: dkershner6/use-npm-token-action@99c5b17c84a15e44fdcef6712b34b76f8f0493b0
      uses: dkershner6/use-npm-token-action@v1
      with:
        # An NPM token with whatever access is needed for your GitHub Action workflow
        token: ${{ secrets.REGISTRY_TOKEN }}
        # The location of your Node workspace (needs to be a sibling of package.json)
  #      workspace: # optional, default is ./
    - name: Set npm configuration
      run: |
        if [ -n "$NPM_REGISTRY" ]; then
          npm config set strict-ssl false
        fi
    - run: npm publish --access=public --registry=$NPM_REGISTRY
